### ISSUE TITLE
Checkboxes in hdriver are inconsistant and unclear

### ISSUE THREAD

**Issue by martinjohndyer** [HiPERCAM/hcam_widgets#12]
Left is hdriver, right is hfinder

![checkboxes](https://user-images.githubusercontent.com/15014527/47865867-46d6ac00-ddf5-11e8-9539-b83927e0f3c8.png)

Maybe it's just me, but the checkboxes in hdriver are rather unclear. Blue for unselected and white (but empty) for selected. When I saw the empty white boxes I assumed they were unselected and selecting them would add a checkmark, which is how it works in hfinder (and seems pretty intuative). The blue filled boxes (same as the background) I assumed were disabled.

**Comment by StuartLittlefair** [comment]
One on the rack PC and one on your laptop or the DRPC yes?

It’s exactly the same code - it’s actually the same module imported for both. This is just how the GUI toolkit renders the widgets.

**Comment by martinjohndyer** [comment]
Ah, I get it. It must just be the version on the rack. Annoying, but it's just a minor thing.
